apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontapp-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: frontapp.compnet.kz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontapp
                port:
                  number: 80

